/*! canvas 2018-07-24 */

"use strict";function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function")}function _possibleConstructorReturn(a,b){if(!a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!b||"object"!=typeof b&&"function"!=typeof b?a:b}function _inherits(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);
a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}}),b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}var _createClass=function(){function a(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1,d.configurable=!0,"value"in d&&(d.writable=!0),Object.defineProperty(a,d.key,d)}}return function(b,c,d){return c&&a(b.prototype,c),
d&&a(b,d),b}}(),_get=function a(b,c,d){null===b&&(b=Function.prototype);var e=Object.getOwnPropertyDescriptor(b,c);if(void 0===e){var f=Object.getPrototypeOf(b);return null===f?void 0:a(f,c,d)}if("value"in e)return e.value;var g=e.get;if(void 0!==g)return g.call(d)},Connection=function(a){function b(a,c,d){_classCallCheck(this,b);var e=_possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).call(this,a,c,d));
return e.config=void 0,e.elements=[],e.drawElements=[],e.answers=[],e.modelAnswers=[],e.modelConnections=[],e.connectorArray=[],e.receiverArray=[],e.connections=[],e.responseDetail={},e.submitButton={position:{x:0,y:0},xLength:0,yLength:0},e.switchButton=void 0,e.randomiseStart=!1,e.repositionIncorrectAnswers=!1,e.stacked=!1,e.dragging=!1,e.active=void 0,e.dragOffset={},e.dragOrigin={},e.answered=!1,
e.rightAnswer=!1,e.submitable=!1,e.controlIndex=-1,e.uid=0,e.currentTime=new Date,e.lastTime=new Date,e.stackIndex=-1,e.mouseOverKey=!1,e.responseIndex=-1,e.displayHelp=!1,e}return _inherits(b,a),_createClass(b,[{key:"configure",value:function(a,c){if(!c.canvas)return void this.configurePlaceholderCanvas(this,"The interactive could not be found");var d=c.canvas;this.userOptions=a,this.canvasData=c,
this.multiple=0!==c.canvas.canvasConfig,this.mesh=2===c.canvas.canvasConfig,this.config=d.config,this.connections=[],this.anyDocked=!1,this.setupElements(d),this.canvasHeight=d.canvasHeight,this.setOptions(c.canvas.options),this.randomiseStart&&this.randomisePositions(),this.setModelAnswers(),this.gotItButton=new Button(this.context,{x:200,y:this.canvasHeight-60},"Got It"),this.gotItButton.fillStyle=this.context.fillStyle="rgb(105,45,145)",
this.gotItButton.strokeStyle=CogPalette.white,this.switchButton=new SwitchButton(this.context,"answers","responses",{x:500,y:this.canvasHeight+50},200,36),this.addHelp(this),_get(b.prototype.__proto__||Object.getPrototypeOf(b.prototype),"configure",this).call(this,this.feedback.length>0),this.eventManager.register(this.submitButton,["mouseDown","mouseMove","mouseUp"]),this.submitButton.fillStyle=CogPalette.submitButtonDisabled,
this.setUserOptions(a),this.drawLoading()}},{key:"addHelp",value:function(a){var c=document.getElementsByTagName("body")[0],d=document.createElement("i");d.setAttribute("id","interactiveHelpButton"),d.setAttribute("class","interactive-control fa fa-question-circle"),d.style.position="absolute",d.style.zIndex=9999,d.style.top=this.canvasPos.y+this.canvasHeight+50+"px",d.style.left=this.canvasPos.x+710+"px",
d.addEventListener("click",a.showHelp.bind(a)),c.appendChild(d);var e=Math.sqrt((720-this.connectorArray[0].connector.position.x+30)*(720-this.connectorArray[0].connector.position.x+30)+(this.canvasHeight+40-this.connectorArray[0].connector.position.y)*(this.canvasHeight+40-this.connectorArray[0].connector.position.y));this.help=[];var f={};f.x=this.connectorArray[0].connector.position.x+50,f.y=this.connectorArray[0].connector.position.y;
var g={};g.x=720,g.y=this.canvasHeight+40;var h={},i={},j={};j.x=f.x+.25*e,j.y=f.y+.25*e;var k={};k.x=.75*g.x,k.y=.75*g.y,h=rotatePoint(j,f,Math.PI/4*-1),i=rotatePoint(k,g,Math.PI/4);var l=[];l.push(rotatePoint({x:f.x+(h.x-f.x)/8,y:f.y+(h.y-f.y)/8},f,Math.PI)),l.push(rotatePoint({x:f.x+(h.x-f.x)/20,y:f.y+(h.y-f.y)/20},f,Math.PI/2)),l.push(rotatePoint({x:f.x+(h.x-f.x)/20,y:f.y+(h.y-f.y)/20},f,Math.PI/2*-1)),
this.help.push({startPoint:f,endPoint:g,control1:h,control2:i,arrow:l}),e=Math.sqrt((this.receiverArray[0].connector.position.x-20)*(this.receiverArray[0].connector.position.x-20)*(this.receiverArray[0].connector.position.y*this.receiverArray[0].connector.position.y));var m={},n={x:20,y:0};this.connectorArrows=[];for(var o=0;o<this.receiverArray.length;o++)l=new ClientArrow({x:this.receiverArray[o].connector.position.x-100,
y:this.receiverArray[o].connector.position.y}),l.endPosition={x:this.receiverArray[o].connector.position.x-20,y:this.receiverArray[o].connector.position.y},l.fillStyle="rgb(105,45,145)",l.strokeStyle="rgb(105,45,145)",this.connectorArrows.push(l);this.help.push({startPoint:m,endPoint:n,control1:h,control2:i,arrow:l}),l=[],l.push({x:300,y:this.canvasHeight+30}),l.push({x:290,y:this.canvasHeight+10}),
l.push({x:310,y:this.canvasHeight+10}),h={x:500,y:50},i={x:300,y:this.canvasHeight-40},this.help.push({startPoint:{x:730,y:50},endPoint:{x:300,y:this.canvasHeight+10},control1:h,control2:i,arrow:l}),_get(b.prototype.__proto__||Object.getPrototypeOf(b.prototype),"addHelp",this).call(this)}},{key:"setModelAnswers",value:function(){this.connections=[],this.modelConnections=[],this.modelAnswers=[];for(var a=0;a<this.connectorArray.length;a++)for(var b=0;b<this.receiverArray.length;b++)if(this.connectorArray[a].arrayGroup===this.receiverArray[b].arrayGroup){
this.modelConnections.push({start:{x:this.connectorArray[a].connector.position.x,y:this.connectorArray[a].connector.position.y},end:{x:this.receiverArray[b].connector.position.x,y:this.receiverArray[b].connector.position.y},connector:a,receiver:b});var c=new ClientBoxReceiver(this.context,this.receiverArray[b].position,this.receiverArray[b].xLength,this.receiverArray[b].yLength);this.receiverArray[b].text&&(c.text=this.copyText(this.context,this.receiverArray[b],c)),
this.receiverArray[b].image&&(c.image=this.receiverArray[b].image),this.receiverArray[b].fillStyle?(c.fillStyle=CogPalette.CBGreen100,c.strokeStyle=CogPalette.CBGreen500):(c.fillStyle=void 0,c.strokeStyle=void 0),c.connector=new ClientCircle(this.receiverArray[b].connector.position,this.receiverArray[b].connector.radius,CogPalette.CBGreen300,CogPalette.CBGreen700,2),this.modelAnswers.push(c)}}},{key:"setOptions",
value:function(a){if(a.attempts){this.attemptThreshold=Number(a.attempts);var b=a.attempts>1?" attempts ":" attempt ";this.notificationText="You have "+a.attempts+b+"at this question."}else this.attempts=" attempt(s) ";a.passthreshold&&(this.passThreshold=Number(a.passthreshold)),1===Number(a.position)&&(this.randomiseStart=!0),a.reposition&&(this.repositionIncorrectAnswers=!0)}},{key:"setupElements",
value:function(a){var c=0,d=a.elements;this.drawElements=[],this.feedback=[],this.rollovers=[],this.rollcontent=[],this.connectorArray=[],this.receiverArray=[];var e=!0,f=!1,g=void 0;try{for(var h,i=d[Symbol.iterator]();!(e=(h=i.next()).done);e=!0){var j=h.value;if("BoxConnector"===j.canvasItemType){var k=new ClientBoxConnector(this.context,{x:j.itemX,y:j.itemY},j.itemXOffset,j.itemYOffset);if(k.index=c++,
k.strokeStyle=this.palette.connector_stroke,3===j.contentType){var l=JSON.parse(j.content);k.text=this.textLoader.processText(this.context,k,l.text,j.itemAlignment,CogPalette.white,!0),k.addImage(this.context,l.image,this)}else 1===j.contentType?k.text=this.textLoader.processText(this.context,k,JSON.parse(j.content),j.itemAlignment,CogPalette.black):2===j.contentType&&(k.addImage(this.context,j.content,this),
k.lineWidth=4);k.itemOrder=j.itemOrder,k.arrayGroup=j.arrayGroup,k.rollIndex=j.rollIndex,this.connectorArray.push(k),k.rollIndex&&(k.hasRollover=!0,this.rollcontent.push(k))}else if("BoxReceiver"===j.canvasItemType){var m=new ClientBoxReceiver(this.context,{x:j.itemX,y:j.itemY},j.itemXOffset,j.itemYOffset);if(m.arrayGroup=j.arrayGroup,m.rollIndex=j.rollIndex,m.itemOrder=j.itemOrder,m.rollIndex&&(m.hasRollover=!0,
this.rollcontent.push(m)),3===j.contentType){var n=JSON.parse(j.content);m.text=this.textLoader.processText(this.context,m,n.text,j.itemAlignment,CogPalette.black,!0),m.addImage(this.context,n.image,this)}else 1===j.contentType?m.text=this.textLoader.processText(this.context,m,JSON.parse(j.content),j.itemAlignment,CogPalette.black,null,10):2===j.contentType&&(m.addImage(this.context,j.content,this),
m.lineWidth=4);(!m.image&&!m.text||m.text&&0===m.text.textArray.length)&&(m.fillStyle=void 0,m.strokeStyle=void 0,m.lineWidth=0),this.receiverArray.push(m)}if("RolloverBox"===j.canvasItemType){var o=new ClientRollover(this.context,{x:j.itemX,y:j.itemY},j.itemXOffset,j.itemYOffset);o.fillStyle=this.palette.rollover_fill,o.strokeStyle=this.palette.rollover_stroke,o.lineWidth=1,o.rollIndex=j.rollIndex,
o.text=this.textLoader.processText(this.context,o,JSON.parse(j.content),j.itemAlignment,this.palette.rollover_stroke),o.yLength=20+o.text.maxHeight,this.rollovers.push(o)}}}catch(a){f=!0,g=a}finally{try{!e&&i.return&&i.return()}finally{if(f)throw g}}_get(b.prototype.__proto__||Object.getPrototypeOf(b.prototype),"setupElements",this).call(this,d);for(var p=0;p<this.connectorArray.length;p++)for(var q=0;q<this.receiverArray.length;q++)if(this.connectorArray[p].arrayGroup===this.receiverArray[q].arrayGroup){
var r=[];this.connectorArray[p].position.x>370?r[0]={x:this.connectorArray[p].position.x,y:this.connectorArray[p].position.y+this.connectorArray[p].yLength/2}:r[0]={x:this.connectorArray[p].position.x+this.connectorArray[p].xLength,y:this.connectorArray[p].position.y+this.connectorArray[p].yLength/2},this.receiverArray[q].position.x+this.receiverArray[q].xLength>360?r[1]={x:this.receiverArray[q].position.x,
y:this.receiverArray[q].position.y+this.receiverArray[q].yLength/2}:r[1]={x:this.receiverArray[q].position.x+this.receiverArray[q].xLength,y:this.receiverArray[q].position.y+this.receiverArray[q].yLength/2},this.connectorArray[p].connector=new ClientCircle(r[0],10,this.palette.white,this.palette.connector_circle_stroke,2),this.receiverArray[q].connector=new ClientCircle(r[1],10,this.palette.white,this.palette.connector_circle_stroke,2);
}}},{key:"randomisePositions",value:function(){var a=[],b=!0,c=!1,d=void 0;try{for(var e,f=this.receiverArray[Symbol.iterator]();!(b=(e=f.next()).done);b=!0){var g=e.value;a.push(g.position)}}catch(a){c=!0,d=a}finally{try{!b&&f.return&&f.return()}finally{if(c)throw d}}for(var h=0;h<this.receiverArray.length;h++){var i=a.splice(getRandomInt(0,this.receiverArray.length-1-h),1);this.receiverArray[h].position={
x:i[0].x,y:i[0].y},this.receiverArray[h].connector.position.y=i[0].y+this.receiverArray[h].yLength/2}}},{key:"draw",value:function(){this.clear(this.context);var a=!0,b=!1,c=void 0;try{for(var d,e=this.drawElements[Symbol.iterator]();!(a=(d=e.next()).done);a=!0){var f=d.value;f.draw(this.context)}}catch(a){b=!0,c=a}finally{try{!a&&e.return&&e.return()}finally{if(b)throw c}}if(this.switchButton.isSwitched()||this.rightAnswer){
this.context.lineWidth=2,this.context.strokeStyle=this.palette.CBGreen700;var g=!0,h=!1,i=void 0;try{for(var j,k=this.modelConnections[Symbol.iterator]();!(g=(j=k.next()).done);g=!0){var l=j.value;this.context.beginPath(),this.context.moveTo(l.start.x,l.start.y),this.context.lineTo(l.end.x,l.end.y),this.context.stroke()}}catch(a){h=!0,i=a}finally{try{!g&&k.return&&k.return()}finally{if(h)throw i}}var m=!0,n=!1,o=void 0;
try{for(var p,q=this.modelAnswers[Symbol.iterator]();!(m=(p=q.next()).done);m=!0){var r=p.value;r.draw(this.context,!0)}}catch(a){n=!0,o=a}finally{try{!m&&q.return&&q.return()}finally{if(n)throw o}}}else{this.context.lineWidth=2,this.context.strokeStyle=this.palette.connector_connection_stroke;for(var s=0;s<this.connections.length;s++)this.breakIndex===s&&void 0!==this.context.setLineDash&&this.context.setLineDash([4,4]),
this.context.beginPath(),this.context.moveTo(this.connections[s].start.x,this.connections[s].start.y),this.context.lineTo(this.connections[s].end.x,this.connections[s].end.y),this.context.stroke(),void 0!==this.context.setLineDash&&this.context.setLineDash([]);var t=!0,u=!1,v=void 0;try{for(var w,x=this.receiverArray[Symbol.iterator]();!(t=(w=x.next()).done);t=!0){var y=w.value;y.draw(this.context),
y.hasRollover&&this.context.drawImage(this.faEllipsis,y.position.x+y.xLength-28,y.position.y+y.yLength-15,25,18)}}catch(a){u=!0,v=a}finally{try{!t&&x.return&&x.return()}finally{if(u)throw v}}}var z=!0,A=!1,B=void 0;try{for(var C,D=this.connectorArray[Symbol.iterator]();!(z=(C=D.next()).done);z=!0){var E=C.value;E.draw(this.context),E.hasRollover&&this.context.drawImage(this.faEllipsisResponse,E.position.x+E.xLength-28,E.position.y+E.yLength-15,25,18);
}}catch(a){A=!0,B=a}finally{try{!z&&D.return&&D.return()}finally{if(A)throw B}}this.attempts>0&&this.drawFeedback(),this.drawBottomLine(),this.submitButton.draw(this.context),this.answered&&!this.rightAnswer&&this.switchButton.draw(this.context),this.notificationBar.draw(this.context),this.notifications.draw(this.context),this.dragging||(this.currentTime=new Date,(this.currentTime.getTime()-this.lastTime.getTime()>1e3||this.mouseOverKey)&&this.rollovers[this.responseDetailIndex]&&this.showResponseDetail&&this.rollovers[this.responseDetailIndex].draw(this.context)),
this.displayHelp&&(this.limitedHelp?this.helpStage=3:this.anyDocked?this.helpStage=2:this.dragging?this.helpStage=1:this.helpStage=0,this.drawHelp()),this.dragging&&(this.context.lineWidth=3,this.context.strokeStyle=this.palette.connector_stroke_active,this.context.beginPath(),this.context.moveTo(this.dragOrigin.x,this.dragOrigin.y),this.context.lineTo(this.dragPos.x,this.dragPos.y),this.context.stroke(),
this.context.fillStyle=this.palette.connector_fill_active,this.context.beginPath(),this.context.arc(this.dragPos.x,this.dragPos.y,11,0,2*Math.PI),this.context.fill()),window.requestAnimationFrame(this.draw.bind(this))}},{key:"drawFeedback",value:function(){var a;a=this.switchButton.isSwitched()?this.modelConnections:this.receiverArray;for(var c=0;c<a.length;c++)a[c].correct||this.switchButton.isSwitched()?this.receiverArray[c].correct&&this.context.drawImage(this.faCheck,this.receiverArray[c].connector.position.x-6,this.receiverArray[c].connector.position.y-6,11,11):this.answered&&this.context.drawImage(this.faExclamation,this.receiverArray[c].connector.position.x-6,this.receiverArray[c].connector.position.y-6,12,12);
_get(b.prototype.__proto__||Object.getPrototypeOf(b.prototype),"drawFeedback",this).call(this)}},{key:"drawHelp",value:function(){if(this.context.fillStyle=this.palette.white,this.context.fillRect(100,this.canvasHeight+40,500,50),this.helpStage)if(1===this.helpStage){this.context.strokeStyle="rgb(105,45,145)",this.context.fillStyle="rgb(105,45,145)",this.context.lineWidth=2;for(var a=0;a<this.receiverArray.length;a++)this.context.strokeStyle="rgb(105,45,145)",
this.context.fillStyle="rgb(105,45,145)",this.context.lineWidth=2,this.context.beginPath(),this.context.arc(this.receiverArray[a].connector.position.x,this.receiverArray[a].connector.position.y,this.receiverArray[a].connector.radius,0,2*Math.PI),this.context.fill(),this.context.stroke(),this.context.beginPath(),this.connectorArrows[a].draw(this.context);this.context.font="300 12pt Open Sans",this.context.fillText("These items link together.",120,this.canvasHeight+63),
this.context.fillText("Drag to the item that links to this concept. ",120,this.canvasHeight+83)}else 2===this.helpStage?(this.drawHelpArrow(2),this.context.fillStyle=this.palette.white,this.context.fillRect(120,this.canvasHeight+45,550,60),this.context.fillStyle="rgb(105,45,145)",this.context.font="300 12pt Open Sans",this.context.fillText("Yes, you've got it - now complete the rest of the question.",120,this.canvasHeight+63),
this.context.fillText("Once you've finished, hit the 'Submit' button to check your answers.",120,this.canvasHeight+83),this.gotItButton.draw(this.context)):3===this.helpStage&&(this.context.fillStyle=CogPalette.white,this.context.fillRect(120,this.canvasHeight+45,550,60),this.context.font="300 12pt Open Sans",this.drawResetHelp());else this.drawHelpArrow(0),this.context.fillStyle="rgb(105,45,145)",
this.context.font="300 12pt Open Sans",this.context.fillText("Match the connecting items by connecting them",120,this.canvasHeight+63),this.context.fillText("together. Click and hold on the circle indicated.",120,this.canvasHeight+83)}},{key:"submit",value:function(){var a=function(){if(this.repositionIncorrectAnswers&&!this.answered)for(var a=0;a<this.connections.length;a++)this.connections[a].correct||(this.receiverArray[this.connections[a].receiver].connector.fillStyle=this.palette.white,
this.connections.splice(a,1),a--)};_get(b.prototype.__proto__||Object.getPrototypeOf(b.prototype),"submit",this).call(this,!1,a.bind(this))}},{key:"prepareJSONResponse",value:function(){var a={};a.attempts=this.attempts,a.responses=[],a.correct=this.rightAnswer;for(var b,c=0;c<this.connections.length;c++)b={},b.responseNumber=this.connections[c].connector,b.dockingNumber=this.connections[c].receiver,
b.correct=!!this.connections[c].correct,a.responses.push(b);return a}},{key:"setUserResponses",value:function(a,b){var c=!0,d=!1,e=void 0;try{for(var f,g=a[Symbol.iterator]();!(c=(f=g.next()).done);c=!0)for(var h=f.value,i=h.connections,j=0;j<i.length;j++)this.setConnection(h.responseNumber,i[j]),this.limitedHelp=!0}catch(a){d=!0,e=a}finally{try{!c&&g.return&&g.return()}finally{if(d)throw e}}}},{key:"setConnection",
value:function(a,b){for(var c=0;c<this.connectorArray.length;c++){for(var d=!1,e=0;e<this.receiverArray.length;e++)this.connectorArray[c].itemOrder===a&&this.receiverArray[e].itemOrder===b&&(this.connections.push({start:{x:this.connectorArray[c].connector.position.x,y:this.connectorArray[c].connector.position.y},end:{x:this.receiverArray[e].connector.position.x,y:this.receiverArray[e].connector.position.y
},connector:c,receiver:e}),d=!0,this.receiverArray[e].isDocked=!0,this.connectorArray[c].isDocked=!0,this.receiverArray[e].connector.fillStyle=this.palette.connector_connected_fill);this.connectorArray[c].isDocked&&(this.connectorArray[c].connector.fillStyle=this.palette.connector_connected_fill)}}},{key:"setCorrectAnswer",value:function(a){this.connections[a].correct=!0,this.multiple||(this.connectorArray[this.connections[a].connector].correct=!0),
this.receiverArray[this.connections[a].receiver].fillStyle&&(this.receiverArray[this.connections[a].receiver].strokeStyle=this.palette.CBGreen500,this.receiverArray[this.connections[a].receiver].fillStyle=this.palette.correct_fill),this.receiverArray[this.connections[a].receiver].correct=!0,this.receiverArray[this.connections[a].receiver].connector.strokeStyle=this.palette.correct_stroke,this.receiverArray[this.connections[a].receiver].connector.fillStyle=this.palette.CBGreen300,
this.receiverArray[this.connections[a].receiver].setFontColor(this.palette.correct_font)}},{key:"checkAnswers",value:function(){var a,b=0;for(a=0;a<this.connections.length;a++)for(var c=0;c<this.modelConnections.length;c++)this.connections[a].connector===this.modelConnections[c].connector&&this.connections[a].receiver===this.modelConnections[c].receiver&&(b++,this.setCorrectAnswer(a));var d=!0,e=!1,f=void 0;
try{for(var g,h=this.connections[Symbol.iterator]();!(d=(g=h.next()).done);d=!0){var i=g.value;i.correct||(this.receiverArray[i.receiver].isDocked=!1,this.connectorArray[i.connector].isDocked=!1,this.connectorArray[i.connector].connector.fillStyle=this.palette.white,this.attempts>=this.attemptThreshold&&(this.receiverArray[i.receiver].fillStyle&&(this.receiverArray[i.receiver].fillStyle=this.palette.CBRed100,
this.receiverArray[i.receiver].strokeStyle=this.palette.CBRed500),this.receiverArray[i.receiver].connector.strokeStyle=this.palette.CBRed500,this.receiverArray[i.receiver].connector.fillStyle=this.palette.CBRed300,this.receiverArray[i.receiver].setFontColor(this.palette.incorrect_font)))}}catch(a){e=!0,f=a}finally{try{!d&&h.return&&h.return()}finally{if(e)throw f}}if(this.attempts>=this.attemptThreshold)for(a=0;a<this.receiverArray.length;a++)this.receiverArray[a].correct||(this.receiverArray[this.connections[a].receiver].fillStyle&&(this.receiverArray[a].fillStyle=this.palette.CBRed100,
this.receiverArray[a].strokeStyle=this.palette.CBRed500),this.receiverArray[a].connector.strokeStyle=this.palette.CBRed500,this.receiverArray[a].connector.fillStyle=this.palette.CBRed100);return b>=this.passThreshold||(this.repositionIncorrectAnswers&&(this.submitable=!1,this.submitButton.fillStyle=this.palette.submitButtonDisabled),!1)}},{key:"mouseDown",value:function(a){if(this.eventManager.mouseDown(this.context,a,{
dragging:this.dragging,dragObject:this.dragObject,answered:this.answered,submitable:this.submitable}),_get(b.prototype.__proto__||Object.getPrototypeOf(b.prototype),"mouseDown",this).call(this,a),!this.dragging&&!this.answered){this.dragIndex=-1;for(var c=-1,d=this.isTouch?10:0,e=0;e<this.connectorArray.length;e++)if(circleIsHit(this.connectorArray[e].connector,a,d)&&!this.connectorArray[e].correct&&(this.dragIndex=e,
this.connectorArray[e].connector.fillStyle=this.palette.connector_fill_active,this.connectorArray[e].connector.strokeStyle=this.palette.connector_stroke_active,!this.multiple))for(var f=0;f<this.connections.length;f++)this.connections[f].connector===e&&(c=f);c>-1&&(this.connectorArray[this.connections[c].connector].isDocked=!1,this.receiverArray[this.connections[c].receiver].isDocked=!1,this.receiverArray[this.connections[c].receiver].connector.fillStyle=this.palette.connector_void_fill,
this.connections.splice(c,1)),this.dragIndex>-1&&(this.dragging=!0,this.dragPos=a,this.dragOffset={x:a.x-this.connectorArray[this.dragIndex].connector.position.x,y:a.y-this.connectorArray[this.dragIndex].connector.position.y},this.dragOrigin={x:this.connectorArray[this.dragIndex].connector.position.x,y:this.connectorArray[this.dragIndex].connector.position.y})}2===this.helpStage&&this.displayHelp&&boxIsHit(this.gotItButton,a)&&(this.showHelp(),
this.limitedHelp=!0),boxIsHit(this.submitButton,a)&&this.submitable&&this.submit(),this.feedback.length&&(boxIsHit(this.feedbackButton,a)&&this.showFeedbackButton&&!this.answered&&(this.showFeedback=!this.showFeedback),boxIsHit(this.feedbackGotItButton,a)&&this.showFeedback&&(this.showFeedback=!this.showFeedback)),this.answered&&!this.rightAnswer&&boxIsHit(this.switchButton.container,a)&&this.toggleAnswers();
}},{key:"handleRollovers",value:function(a){this.responseDetailIndex=-1;for(var b=!1,c=this.rollcontent.length-1;c>=0;c--)if(boxIsHit(this.rollcontent[c],a))for(var d=0;d<this.rollovers.length;d++)this.rollcontent[c].rollIndex===this.rollovers[d].rollIndex&&(this.stacked&&!this.rollcontent[c].showRollover&&this.rollcontent[c]instanceof ClientResponseBox||(this.showResponseDetail=!0,this.responseDetailIndex=d,
this.startTimer&&(this.startTimer=!1,this.lastTime=new Date),this.responseDetail={},this.responseDetail.x=a.x+this.rollovers[d].xLength>736?-50:50,this.responseDetail.y=a.y>480?this.rollovers[d].yLength*-1+10:this.rollcontent[c].yLength+10,this.rollovers[d].position={x:this.rollcontent[c].position.x+this.responseDetail.x,y:this.rollcontent[c].position.y+this.responseDetail.y},b=!0));return b}},{key:"mouseMove",
value:function(a){var b,c;if(this.eventManager.mouseMove(this.context,a,{dragging:this.dragging,submitable:this.submitable}),this.dragging)for(this.dragPos=a,this.startTimer=!0,this.showResponseDetail=!1,this.canvas.style.cursor="default",this.itemSwitchHover=!1,this.breakIndex=-1,b=0;b<this.receiverArray.length;b++)if(circleIsHit(this.receiverArray[b].connector,a)&&!this.receiverArray[b].correct)for(this.receiverArray[b].connector.fillStyle=this.palette.connector_fill_active,
this.receiverArray[b].connector.strokeStyle=this.palette.connector_stroke_active,c=0;c<this.connections.length;c++)this.connections[c].connector===this.dragIndex||this.connections[c].receiver!==b||this.receiverArray[b].correct||(this.breakIndex=c);else this.receiverArray[b].correct||(this.receiverArray[b].connector.fillStyle=this.receiverArray[b].isDocked?this.palette.connector_connected_fill:this.palette.connector_fill,
this.receiverArray[b].connector.strokeStyle=this.palette.connector_stroke);else{var d=!1;if(d=this.handleRollovers(a),this.answered){for(d=!1,b=0;b<this.receiverArray.length;b++)if(boxIsHit(this.receiverArray[b],a)){this.receiverArray[b].mouseOver=!0;var e=this.switchButton.isSwitched()?this.modelConnections:this.connections,f=this.switchButton.isSwitched()?this.palette.correct_fill:this.palette.connector_answer_connected_fill,g=this.switchButton.isSwitched()?this.palette.correct_stroke:this.palette.connector_answer_connected_stroke;
for(c=0;c<e.length;c++)e[c].receiver===b&&(this.connectorArray[e[c].connector].fillStyle=f,this.connectorArray[e[c].connector].strokeStyle=g,this.connectorArray[e[c].connector].connector.strokeStyle=g,this.connectorArray[e[c].connector].connector.fillStyle=f,d=!0)}else this.receiverArray[b].mouseOver=!1;if(!d){var h=!0,i=!1,j=void 0;try{for(var k,l=this.connectorArray[Symbol.iterator]();!(h=(k=l.next()).done);h=!0){
var m=k.value;m.fillStyle=this.palette.white,m.strokeStyle=this.palette.connector_stroke,m.connector.strokeStyle=this.palette.connector_stroke,m.connector.fillStyle=this.palette.white}}catch(a){i=!0,j=a}finally{try{!h&&l.return&&l.return()}finally{if(i)throw j}}this.showResponseDetail=!1,this.responseDetailIndex=-1,this.startTimer=!0}}else{var n=!0,o=!1,p=void 0;try{for(var q,r=this.connectorArray[Symbol.iterator]();!(n=(q=r.next()).done);n=!0){
var s=q.value;circleIsHit(s.connector,a)?(s.connector.fillStyle=this.palette.connector_fill_active,s.connector.strokeStyle=this.palette.connector_stroke_active):(s.connector.strokeStyle=this.palette.connector_stroke,s.connector.fillStyle=s.isDocked?this.palette.CBBlue100:this.palette.white)}}catch(a){o=!0,p=a}finally{try{!n&&r.return&&r.return()}finally{if(o)throw p}}var t=!0,u=!1,v=void 0;try{for(var w,x=this.receiverArray[Symbol.iterator]();!(t=(w=x.next()).done);t=!0){
var y=w.value;y.mouseOver=boxIsHit(y,a)}}catch(a){u=!0,v=a}finally{try{!t&&x.return&&x.return()}finally{if(u)throw v}}d||(this.showResponseDetail=!1,this.responseDetailIndex=-1,this.startTimer=!0)}}this.answered||(this.submitButton.fill=boxIsHit(this.submitButton,a)?this.palette.submitButtonHover:this.palette.submitButton);var z=!0,A=!1,B=void 0;try{for(var C,D=this.modelAnswers[Symbol.iterator]();!(z=(C=D.next()).done);z=!0){
var E=C.value;E.mouseOver=boxIsHit(E,a)}}catch(a){A=!0,B=a}finally{try{!z&&D.return&&D.return()}finally{if(A)throw B}}}},{key:"setStackItem",value:function(){if(this.stacked){this.stackIndex>-1&&(this.responseArray[this.stackIndex].stackIndex=!1);for(var a=this.responseArray.length-1;a>=0;a--)if(this.responseArray[a].position.x===this.responseArray[a].originalPosition.x&&this.responseArray[a].position.y===this.responseArray[a].originalPosition.y){
this.stackIndex=a,this.responseArray[a].showRollover=!0;break}}}},{key:"mouseUp",value:function(a){this.eventManager.mouseUp(this.context,a,{dragging:this.dragging,dragObject:this.dragObject,answered:this.answered});var b=-1;if(this.dragging){for(var c=this.isTouch?10:0,d=0;d<this.receiverArray.length;d++)circleIsHit(this.receiverArray[d].connector,a,c)&&!this.receiverArray[d].correct?(b=d,this.receiverArray[d].isDocked=!0,
this.receiverArray[d].connector.strokeStyle=this.palette.connector_connected_stroke,this.receiverArray[d].connector.fillStyle=this.palette.connector_connected_fill,this.connectorArray[this.dragIndex].connector.fillStyle=this.palette.CBBlue100,this.connectorArray[this.dragIndex].isDocked=!0,this.connections.push({start:{x:this.dragOrigin.x,y:this.dragOrigin.y},end:{x:this.receiverArray[d].connector.position.x,
y:this.receiverArray[d].connector.position.y},connector:this.dragIndex,receiver:d}),this.displayHelp||(this.limitedHelp=!0),this.anyDocked=!0):this.connectorArray[this.dragIndex].isDocked||(this.connectorArray[this.dragIndex].connector.fillStyle=this.palette.white);if(this.connectorArray[this.dragIndex].connector.strokeStyle=this.palette.connector_stroke,this.breakIndex>-1&&!this.connections[this.breakIndex].correct){
var e,f=this.connections[this.breakIndex].connector;this.connections.splice(this.breakIndex,1);for(var g=0;g<this.connections.length;g++)this.connections[g].connector===f&&(e=!0);this.connectorArray[f].isDocked=e,this.breakIndex=-1}this.dragIndex=void 0}this.dragging=!1,this.connections.length>=this.receiverArray.length&&!this.answered&&(this.submitable=!0,this.submitButton.fillStyle=this.palette.submitButton);
}},{key:"controlKey",value:function(){this.controlIndex=this.controlIndex<this.connectorArray.length-1?this.controlIndex+=1:0,this.setRolloverKey();var a=!0,b=!1,c=void 0;try{for(var d,e=this.connectorArray[Symbol.iterator]();!(a=(d=e.next()).done);a=!0){var f=d.value;if(f.index===this.controlIndex){if(f.correct)return this.controlKey();f.connector.fillStyle=this.palette.connector_fill_active,f.connector.strokeStyle=this.palette.connector_stroke_active;
}else f.correct||(f.connector.fillStyle=this.palette.connector_fill,f.connector.strokeStyle=this.palette.connector_stroke)}}catch(a){b=!0,c=a}finally{try{!a&&e.return&&e.return()}finally{if(b)throw c}}}},{key:"checkDock",value:function(a){if(a===-1)return!1;for(var b=!1,c=0;c<this.responseArray.length;c++)if(this.responseArray[c].dockPosition===a&&this.responseArray[c]!==this.responseArray[this.responseIndex])return!0;
return b}},{key:"rollOverKey",value:function(){this.rollovers.length&&(this.mouseOverKey=!this.mouseOverKey,this.showResponseDetail=this.mouseOverKey,this.setRolloverKey())}},{key:"setRolloverKey",value:function(){this.mouseOverKey&&this.responseIndex>-1&&(this.responseDetailIndex=this.responseIndex,this.responseDetail={},this.responseDetail.x=this.responseArray[this.responseIndex].position.x>450?-50:50,
this.responseDetail.y=this.responseArray[this.responseIndex].position.y>480?-50:50,this.rollovers[this.responseIndex].position={x:this.responseArray[this.responseIndex].position.x+this.responseDetail.x,y:this.responseArray[this.responseIndex].position.y+this.responseDetail.y})}},{key:"leftKey",value:function(){}},{key:"rightKey",value:function(){if(this.controlIndex>-1&&!this.answered){var a;a=this.connectorArray[this.controlIndex].dockPosition>-1?this.connectorArray[this.controlIndex].dockPosition:-1,
a<this.receiverArray.length-1?a++:a=-1;for(var b=0;this.checkDock(a);){if(!(a<this.receiverArray.length-1)){a=-1;break}a++,b++}a>-1?this.connectorArray[this.controlIndex].dockPosition=a:(this.responseArray[this.controlIndex].dockPosition=void 0,this.responseArray[this.controlIndex].position={x:this.responseArray[this.controlIndex].originalPosition.x,y:this.responseArray[this.controlIndex].originalPosition.y
})}}},{key:"keyDown",value:function(a){}}]),b}(CanvasObject);
//# sourceMappingURL=../../sourcemap.map